name: "Get mods"
description: "Gets mod releases"
inputs:
  out-directory:
    description: "Directory where database files will be written to"
    required: true
  mods:
    description: "Initial JSON mod database to modify"
    required: true
  GITHUB_TOKEN:
    description: "GitHub Token for Octokit authentication"
    required: true
  discord-hook-url:
    description: "Secret Discord hook url with token"
    required: true
  discord-mod-update-role-id:
    description: "ID for the Discord role to ping when there's a mod update"
    required: true
  discord-new-mod-role-id:
    description: "ID for the Discord role to ping when there's a new mod added to the database"
    required: true
  google-service-account:
    description: "Base64-encoded Google service account credentials json"
    required: true
  discord-mod-hook-urls:
    description: "JSON object where keys are the uniqueName of a mod, and the values are the Discord hook urls of the channel where update notifications should be sent to."
    required: true
outputs:
  releases:
    description: "JSON list of latest mod releases"
runs:
  using: "node16"
  main: "build/index.js"
