name: Force new mod notification

on:
  workflow_dispatch:
    inputs:
      modUniqueID:
        description: "The unique id of the mod to notify about"
        required: true
        type: string

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "26"

      - run: npm ci
        working-directory: scripts

      - name: Checkout database repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: master
          path: database

      - name: Send Notifications
        run: >-
          npm run force-new-mod-notification --
          --currentDatabaseFile ../database/database.json
          --modUniqueId '${{ github.event.inputs.modUniqueID }}'
        working-directory: scripts
        env:
          DISCORD_HOOK_URL: ${{ secrets.DISCORD_HOOK_URL }}
          DISCORD_NEW_MOD_ROLE_ID: ${{ secrets.DISCORD_NEW_MOD_ROLE_ID }}
          DISCORD_MOD_UPDATE_ROLE_ID: ${{ secrets.DISCORD_MOD_UPDATE_ROLE_ID }}
