name: Force new mod notification

on:
  workflow_dispatch:
    inputs:
      modUniqueID:
        description: "The unique id of the mod to notify about"
        required: true
        type: string

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "26"

      - run: npm ci
        working-directory: scripts

      - name: Checkout database repo
        uses: actions/checkout@v4
        with:
          ref: master
          path: database

      - name: Send Notifications
        run: node scripts/src/send-notifications/force-new-mod-notification.ts
        env:
          INPUT_CURRENT_DATABASE: database/database.json
          INPUT_DISCORD_HOOK_URL: ${{ secrets.DISCORD_HOOK_URL }}
          INPUT_DISCORD_NEW_MOD_ROLE_ID: ${{ secrets.DISCORD_NEW_MOD_ROLE_ID }}
          INPUT_DISCORD_MOD_UPDATE_ROLE_ID: ${{ secrets.DISCORD_MOD_UPDATE_ROLE_ID }}
          INPUT_MOD_UNIQUE_ID: ${{ github.event.inputs.modUniqueID }}
