name: Handle Mod Issue

on:
  issues:
    types: [opened, reopened, edited]
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      issue-number:
        description: "Issue number to process"
        required: true
        type: number

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  handle-mod-issue:
    runs-on: ubuntu-latest
    if: >-
      github.event_name == 'workflow_dispatch' ||
      (
        github.event.issue.state != 'closed' &&
        contains(github.event.issue.labels.*.name, 'add-mod') &&
        github.event.issue.pull_request == null &&
        (
          github.event.comment == null ||
          startsWith(github.event.comment.body, 'checker, retry')
        )
      )

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "26"

      - run: npm ci
        working-directory: scripts

      - name: Handle Mod Issue
        run: >-
          npm run handle-mod-issue --
          --modsFile ../mods.json
          --issueTemplateFile ../.github/ISSUE_TEMPLATE/add-mod.yml
          --issueNumber "${{ github.event.inputs.issue-number || github.event.issue.number }}"
          --commentAuthor "github-actions[bot]"
        working-directory: scripts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
