name: PR from Issue
on:
  issues:
    types: [opened, reopened, edited]
concurrency: "main"
jobs:
  pr_from_issue:
    if: ${{ contains(github.event.issue.labels.*.name, 'add-mod') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "26"

      - uses: stefanbuck/github-issue-parser@cb6e97157cbf851e3a393ff8d57c93a484cc323f # v3.2.5
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/add-mod.yml

      - name: Get local Mod Database file
        id: local-mods
        run: echo "mods_output=$(< ./mods.json sed ':a;N;$!ba;s/\n/ /g')" >> $GITHUB_ENV

      - run: npm ci
        working-directory: scripts

      - id: modify-mod-list
        run: >-
          npm run modify-mod-list --
          --outFile ../mods.json
          --form '${{ steps.issue-parser.outputs.jsonString }}'
        working-directory: scripts
        env:
          MODS: ${{ env.mods_output }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          title: "Add/Edit mod: ${{fromJSON(steps.issue-parser.outputs.jsonString).uniqueName}}"
          commit-message: "Add/Edit mod: ${{fromJSON(steps.issue-parser.outputs.jsonString).uniqueName}}"
          body: "Closes #${{ github.event.issue.number }}\n${{fromJSON(steps.issue-parser.outputs.jsonString).repoUrl}}"
          branch-suffix: random
          delete-branch: true
          token: ${{ secrets.GITHUB_TOKEN }}
          committer: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          labels: "add-mod"
