name: PR from Issue
on:
  issues:
    types: [opened, reopened, edited]
concurrency: "main"
jobs:
  pr_from_issue:
    if: ${{ contains(github.event.issue.labels.*.name, 'add-mod') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v6
        with:
          node-version: "26"

      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/add-mod.yml

      - name: Get local Mod Database file
        id: local-mods
        run: echo "mods_output=$(< ./mods.json sed ':a;N;$!ba;s/\n/ /g')" >> $GITHUB_ENV

      - run: npm ci
        working-directory: scripts

      - id: modify-mod-list
        run: npm run modify-mod-list
        working-directory: scripts
        env:
          INPUT_OUT_FILE: ../mods.json
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_FORM: ${{ steps.issue-parser.outputs.jsonString }}
          INPUT_MODS: ${{ env.mods_output }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Add/Edit mod: ${{fromJSON(steps.issue-parser.outputs.jsonString).uniqueName}}"
          commit-message: "Add/Edit mod: ${{fromJSON(steps.issue-parser.outputs.jsonString).uniqueName}}"
          body: "Closes #${{ github.event.issue.number }}\n${{fromJSON(steps.issue-parser.outputs.jsonString).repoUrl}}"
          branch-suffix: random
          delete-branch: true
          token: ${{ secrets.GITHUB_TOKEN }}
          committer: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          labels: "add-mod"
